### ISSUE TITLE
Add support for enums

### ISSUE THREAD

**Issue by mrstegeman** [mozilla-iot/schemas#17]
Should the following optionally support an enum to limit possible values?
* LevelProperty
* BrightnessProperty
* ColorProperty
* ColorTemperatureProperty

Do we even need to specify that enums are acceptable for all types, or should it be optional for everything?

_Inspired by mozilla-iot/gateway#1467_

**Comment by benfrancis** [comment]
Good question. In general I think schemas should try to constrain data types so that clients know what to expect, but I think explicitly saying that particular schemas optionally support enums to further constrain the possible values would be OK. We could make the assumption that all values support enums, but that might add quite a lot of complexity to WoT clients to cater to all possible values. What do you think?

**Comment by mrstegeman** [comment]
I agree that it could add complexity to a client, but I think that's acceptable in this case. It can definitely be helpful to constrain inputs further at times.

For reference, the HAP (HomeKit) spec allows for the following constraints:
* Minimum value (for float and int)
* Maximum value (for float and int)
* Step value (for float and int)
* Max length (for string)
* Max data length (for binary)
* Valid values (for spec-defined enum types)
* Valid values range (for spec-defined enum types)

**Comment by mrstegeman** [comment]
From the JSON Schema spec:

> 6.2.1. multipleOf
>
>The value of "multipleOf" MUST be a number, strictly greater than 0.
>
>A numeric instance is valid only if division by this keyword's value results in an integer.

**Comment by mrstegeman** [comment]
We have some examples in the spec for enums now, so closing this.
