### ISSUE TITLE
HumiditySensor + BarometricSensor

### ISSUE THREAD

**Issue by dhylands** [mozilla-iot/schemas#30]
I just got a xiaomi "weather" sensor which has temperature, humidity, and barometric pressure.

It would be nice to be include TemperatureSensor, HumiditySensor and BarometricSensor in the list of @types so that the user can choose the most important to them.

**Comment by rzr** [comment]
Just curious, can this device be turned on/off ?

I may consider to add humidity driver to this lib:
https://github.com/rzr/generic-sensors-lite#readme

I guess both should be aligned to w3c types shouldn't they ?

**Comment by dhylands** [comment]
The xiaomi weather sensor is battery powered and has no on/off switch. I've been making things MultiLevelSensors and using a LevelProperty until we get specific sensor types.

And yes - if the w3c already has sensors types which perform the desired thing we should use those rather than creating our own.

**Comment by freaktechnik** [comment]
TemperatureSensor already exists (https://github.com/mozilla-iot/schemas/commit/da7e1d3c8dd08025a7d2399939fe86a06ccd2ece) but I agree, humidity and pressure would be nice to have specific properties for. I had held off on suggesting them (for Netatmo) since they're relatively simple cosmetic changes.

**Comment by freaktechnik** [comment]
Humidity is in %, pressure would be Pa (and could be converted to anything by the client layer, but the API layer is in SI units).
